"use client";
import { useEffect, useState } from "react";
import { Bell, CheckCircle2, ChevronRight, X } from "lucide-react";
type Award={id:string;recipient_display_name:string;support_type:string;amount:number|null;currency:string|null;display_amount:string|null;delivery_status:string};
export function RecentAwards(){
 const [awards,setAwards]=useState<Award[]>([]); const [open,setOpen]=useState(false); const [index,setIndex]=useState(0);
 useEffect(()=>{fetch('/api/awards').then(r=>r.ok?r.json():[]).then(d=>setAwards(Array.isArray(d)?d:[])).catch(()=>setAwards([]))},[]);
 useEffect(()=>{if(awards.length<2)return;const t=window.setInterval(()=>setIndex(v=>(v+1)%awards.length),4000);return()=>window.clearInterval(t)},[awards.length]);
 if(!awards.length)return null;
 const award=awards[index]; const money=award.display_amount || (award.amount==null?'Amount not published':new Intl.NumberFormat('en-US',{style:'currency',currency:award.currency||'USD',maximumFractionDigits:0}).format(Number(award.amount)));
 return <><button onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-30 flex max-w-[370px] items-start gap-3 rounded-lg border border-[#c8d7e0] bg-white p-4 text-left shadow-[0_12px_35px_rgba(11,45,69,.16)] hover:border-[#005ea8]"><span className="mt-0.5 grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#eaf1f5] text-[#005ea8]"><Bell size={17}/></span><span className="min-w-0"><span className="block text-[11px] font-bold uppercase tracking-wide text-[#536b79]">Approved beneficiary</span><span className="mt-1 block text-[13px] font-semibold text-[#12304a]">{award.recipient_display_name}</span><span className="mt-1 block text-[11px] text-[#536b79]">{money} · {award.delivery_status}</span></span><ChevronRight size={16} className="mt-1 shrink-0 text-[#7b8e9a]"/></button>{open&&<div className="fixed inset-0 z-50 flex items-end justify-end bg-[#0b2d45]/25 p-4 sm:items-center sm:justify-center" role="dialog" aria-modal="true"><div className="w-full max-w-2xl rounded-xl border border-[#c8d7e0] bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-[#d9e2e8] px-5 py-4"><div><h2 className="font-bold text-[#12304a]">Approved beneficiaries</h2><p className="text-[11px] text-[#647985]">Current published beneficiary records.</p></div><button onClick={()=>setOpen(false)} aria-label="Close" className="rounded-md p-2 hover:bg-[#f4f7f9]"><X size={18}/></button></div><div className="divide-y divide-[#e4eaee] max-h-[70vh] overflow-auto">{awards.map(item=><div key={item.id} className="grid grid-cols-[1fr_auto] gap-4 px-5 py-4 sm:grid-cols-[1fr_auto_auto]"><div><p className="text-sm font-semibold text-[#12304a]">{item.recipient_display_name}</p><p className="text-xs text-[#647985]">Approved beneficiary · {item.delivery_status}</p></div><span className="text-sm font-bold text-[#12304a]">{item.display_amount || (item.amount==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:item.currency||'USD',maximumFractionDigits:0}).format(Number(item.amount)))}</span><CheckCircle2 size={19} className="hidden text-[#2e7d52] sm:block"/></div>)}</div></div></div>}</>
}
