'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, CheckCircle2, Save, XCircle } from 'lucide-react'

const statuses=['submitted','under_review','more_information','approved','declined','support_processing']
export default function AdminApplicationPage({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(''); const [app,setApp]=useState<any>(null); const [status,setStatus]=useState(''); const [notes,setNotes]=useState(''); const [reason,setReason]=useState(''); const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false)
 useEffect(()=>{params.then(p=>{setId(p.id);fetch(`/api/applications/${p.id}`).then(r=>r.json()).then(d=>{setApp(d);setStatus(d.status);setNotes(d.agent_notes||'');setReason(d.decision_reason||'')})})},[params])
 async function save(nextStatus=status){setSaving(true);setMessage('Saving…');const r=await fetch(`/api/applications/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:nextStatus,agent_notes:notes,decision_reason:reason})});const d=await r.json();setMessage(r.ok?`Application ${nextStatus.replaceAll('_',' ')}.`:'Error: '+d.error);if(r.ok){setApp(d);setStatus(d.status)}setSaving(false)}
 if(!app)return <div className="p-10 text-sm">Loading application…</div>
 return <main className="min-h-screen bg-[#F4F7F9] px-4 py-8"><div className="mx-auto max-w-5xl"><Link href="/admin/applications" className="inline-flex items-center gap-2 text-sm font-bold text-[#005EA8]"><ArrowLeft size={16}/> Back to applications</Link><div className="mt-5 rounded-xl border bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-bold text-[#005EA8]">{app.application_number}</div><h1 className="mt-1 text-2xl font-extrabold text-[#12304A]">{app.full_name}</h1><p className="mt-1 text-sm text-slate-500">Submitted {new Date(app.created_at).toLocaleString()}</p></div><span className="rounded-full bg-[#EAF1F5] px-3 py-2 text-xs font-bold capitalize text-[#005EA8]">{app.status.replaceAll('_',' ')}</span></div>
 <div className="mt-6 flex flex-wrap gap-3 border-b border-slate-100 pb-6"><button disabled={saving||app.status==='approved'} onClick={()=>save('approved')} className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-50"><CheckCircle2 size={16}/> Approve application</button><button disabled={saving||app.status==='declined'} onClick={()=>save('declined')} className="inline-flex items-center gap-2 rounded-lg bg-red-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-50"><XCircle size={16}/> Decline application</button></div>
 <div className="mt-7 grid gap-4 md:grid-cols-2">{[['Email',app.email],['Phone',app.phone],['Address',app.address],['City / State',`${app.city||'—'} / ${app.state||'—'}`],['Date of birth',app.date_of_birth||'—'],['Occupation',app.occupation||'—'],['Monthly income',app.monthly_income??'—'],['Status',app.status.replaceAll('_',' ')]].map(([k,v])=><div key={k as string} className="rounded-lg bg-[#F4F7F9] p-4"><div className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{k as string}</div><div className="mt-1 text-sm text-[#12304A]">{v as string}</div></div>)}</div><div className="mt-6 rounded-lg border border-slate-200 p-4"><div className="text-xs font-bold">Reason for support</div><p className="mt-2 text-sm leading-6 text-slate-600">{app.reason||'No reason supplied.'}</p></div><div className="mt-6 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Application status<select value={status} onChange={e=>setStatus(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-3 text-sm">{statuses.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label><label className="text-sm font-semibold">Decision reason<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-3 text-sm" placeholder="Reason shown to applicant when appropriate."/></label></div><label className="mt-4 block text-sm font-semibold">Internal agent notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={5} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-3 text-sm" placeholder="Internal notes; do not include sensitive information that is not needed."/></label><div className="mt-5 flex items-center gap-3"><button disabled={saving} onClick={()=>save()} className="inline-flex items-center gap-2 rounded-lg bg-[#005EA8] px-5 py-3 text-sm font-bold text-white disabled:opacity-50"><Save size={16}/> Save changes</button><span className="text-xs text-slate-500">{message}</span></div></div></div></main>
}
