import { redirect } from 'next/navigation'
import Link from 'next/link'
import { DashboardShell } from '@/components/dashboard-shell'
import { createClient } from '@/lib/supabase/server'

export default async function ApplicationPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect('/login?next=/dashboard/application')
 const {data:app}=await supabase.from('applications').select('*, grants(title,description)').eq('applicant_id',user.id).order('created_at',{ascending:false}).limit(1).maybeSingle()
 return <DashboardShell><div className="p-5 lg:p-8"><Link href="/dashboard" className="text-xs font-bold text-[#005EA8]">← Dashboard</Link><div className="mt-4 max-w-4xl"><h1 className="text-2xl font-extrabold text-[#12304A]">My application</h1>{!app?<div className="mt-6 rounded-xl border bg-white p-7"><h2 className="font-bold">No application yet</h2><p className="mt-2 text-sm text-slate-500">Start your application from the grants page.</p><Link href="/grants" className="mt-5 inline-block rounded-md bg-[#005EA8] px-5 py-3 text-sm font-bold text-white">Find a grant</Link></div>:<div className="mt-6 space-y-4"><section className="rounded-xl border bg-white p-6"><div className="flex flex-wrap justify-between gap-4"><div><div className="text-[11px] font-bold uppercase tracking-wide text-[#005EA8]">Application ID</div><div className="mt-1 text-lg font-extrabold text-[#12304A]">{app.application_number}</div></div><span className="rounded-full bg-[#EAF1F5] px-3 py-2 text-xs font-bold text-[#005EA8]">{app.status.replaceAll('_',' ')}</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{[['Full name',app.full_name],['Email',app.email],['Phone',app.phone],['Address',app.address],['City',app.city],['State',app.state],['Occupation',app.occupation],['Monthly income',app.monthly_income ? `₦${Number(app.monthly_income).toLocaleString()}` : '—'],['Date of birth',app.date_of_birth],['Reason',app.reason]].map(([k,v])=><div key={k as string} className="rounded-lg bg-[#F4F7F9] p-4"><div className="text-[10px] font-bold uppercase text-slate-400">{k as string}</div><div className="mt-1 text-sm text-[#12304A]">{(v||'—') as string}</div></div>)}</div></section><div className="rounded-xl border border-[#c8d7e0] bg-white p-5 text-sm text-[#536b79]">For corrections or additional information, use Messages or respond to a request from the grant team.</div></div>}</div></div></DashboardShell>
}
