import Link from 'next/link'
import { redirect } from 'next/navigation'
import { requireRole } from '@/lib/supabase/server'
import { StaffSignOut } from '@/components/staff-signout'
import { Clock3, FileText, Search } from 'lucide-react'

export default async function AgentPage() {
  const { supabase, user, profile } = await requireRole(['agent','admin'])
  if (!user) redirect('/login?next=/agent'); if (!profile) redirect('/dashboard')
  const { data: apps } = await supabase.from('applications').select('id, application_number, full_name, city, status, created_at, grants(title)').order('created_at',{ascending:false}).limit(25)
  const { count: pending } = await supabase.from('applications').select('*',{count:'exact',head:true}).in('status',['submitted','under_review','more_information'])
  return <main className="min-h-screen bg-[#F4F7F9]"><header className="border-b bg-white"><div className="container-x flex min-h-20 items-center justify-between"><div><div className="text-xs font-bold text-[#005EA8]">CASE MANAGEMENT</div><h1 className="text-xl font-extrabold text-[#12304A]">Agent workspace</h1></div><div className="flex items-center gap-4"><Link href="/dashboard" className="text-sm font-bold text-[#005EA8]">Applicant view</Link>{profile.role==='admin'&&<Link href="/admin" className="text-sm font-bold text-[#005EA8]">Admin</Link>}<StaffSignOut/></div></div></header><div className="container-x py-8"><div className="grid gap-4 md:grid-cols-3"><div className="rounded-xl border bg-white p-5"><FileText className="text-[#005EA8]" size={20}/><div className="mt-4 text-2xl font-extrabold">{apps?.length??0}</div><div className="text-xs text-slate-500">Recent applications</div></div><div className="rounded-xl border bg-white p-5"><Clock3 className="text-[#005EA8]" size={20}/><div className="mt-4 text-2xl font-extrabold">{pending??0}</div><div className="text-xs text-slate-500">Needs attention</div></div><div className="rounded-xl border bg-white p-5"><Search className="text-[#005EA8]" size={20}/><div className="mt-4 text-sm font-bold">Search & review</div><div className="text-xs text-slate-500">Open any application below.</div></div></div><section className="mt-7 overflow-hidden rounded-xl border bg-white"><div className="border-b p-5"><h2 className="font-bold">Application queue</h2><p className="mt-1 text-xs text-slate-500">Newest submissions first.</p></div><div className="divide-y">{(apps??[]).map((a:any)=><Link key={a.id} href={`/agent/applications/${a.id}`} className="grid gap-2 p-5 hover:bg-slate-50 md:grid-cols-[1.1fr_1fr_1fr_auto] md:items-center"><div><div className="text-sm font-bold">{a.full_name}</div><div className="text-xs text-slate-400">{a.application_number}</div></div><div className="text-xs text-slate-500">{a.city || '—'}</div><div className="text-xs text-slate-500">{a.grants?.title || 'General support'}</div><span className="w-fit rounded-full bg-[#EAF1F5] px-3 py-1 text-[11px] font-bold text-[#005EA8]">{a.status.replaceAll('_',' ')}</span></Link>)}{!(apps?.length)&&<div className="p-8 text-sm text-slate-500">No applications yet.</div>}</div></section></div></main>
}
